DROP TABLE RES;
DROP TABLE TRES;
DROP TABLE MEMBER;
DROP TABLE DOCTOR;
DROP TABLE NOTICE;
DROP TABLE QNA;
DROP SEQUENCE SEQ_TRES_NO;
DROP SEQUENCE SEQ_RES_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE QNA_NO;
DROP SEQUENCE SEQ_GROUPNO;

-- 회원
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PW VARCHAR2(30),
    MEMBER_NAME VARCHAR2(20),
    MEMBER_BIRTH DATE,
    MEMBER_GENDER VARCHAR2(6),
    MEMBER_PHONE VARCHAR2(50),
    MEMBER_EMAIL VARCHAR2(50)
);

-- 의사
CREATE TABLE DOCTOR (
    DOCTOR_NO NUMBER PRIMARY KEY,
    DOCTOR_ID VARCHAR2(30) NOT NULL,
    DOCTOR_PW VARCHAR2(30) NOT NULL,
    DOCTOR_NAME VARCHAR2(20) NOT NULL,
    DOCTOR_DPT VARCHAR2(20) NOT NULL,
    DOCTOR_PHONE VARCHAR2(50),
    DOCTOR_EMAIL VARCHAR2(50)
);

--SELECT BIRTH FROM TRES WHERE RES_NAME = 'ㅇㅇ';
--DELETE FROM TRES WHERE RES_NAME ='ㅇㅇ' AND PHONE ='3123123' AND BIRTH = TO_DATE('2022-02-17 00:00:00','YYYY-MM-DD HH24:MI:SS');
--SELECT * FROM TRES WHERE RES_NAME ='1' AND PHONE ='1' AND BIRTH ='2022-02-07';

-- 시퀀스
CREATE SEQUENCE SEQ_TRES_NO
    NOCACHE;

CREATE SEQUENCE SEQ_RES_NO
    NOCACHE;

-- 일반 예약
CREATE TABLE RES(
    RES_NO VARCHAR2(100) PRIMARY KEY,
    RES_MEMID VARCHAR2(30),
    USER_NAME VARCHAR2(100),
    USER_BIR VARCHAR2(1000),
    USER_PHONE VARCHAR2(1000),
    DEPARTMENT VARCHAR2(500),
    DEPT_STAFF VARCHAR2(500),
    DEPT_DATE DATE,
    DEPT_TIMEDATE VARCHAR2(500)
    );
    
-- 동행서비스 예약
CREATE TABLE TRES(
    TRES_MEMID VARCHAR2(20),
    TRES_NO VARCHAR2(100) PRIMARY KEY,
    DEPARTMENT VARCHAR2(100),
    DEPT_STAFF VARCHAR2(100) NOT NULL,
    RES_NAME VARCHAR2(100) NOT NULL,
    DEPT_DATE DATE,
    DEPT_TIME VARCHAR2(500),
    BIRTH VARCHAR2(500),
    PHONE VARCHAR2(200),
    ADDRESS VARCHAR2(1000),
    ACC VARCHAR2(100),
    FILENAME VARCHAR2(1000),
    FILERENAME VARCHAR2(1000)
);
-- 공지사항
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(300) NOT NULL,
    NOTICE_CONTENTS VARCHAR2(2000) NOT NULL,
    NOTICE_WRITER VARCHAR2(40) NOT NULL,
    NOTICE_DATE DATE DEFAULT SYSDATE,
    NOTICE_COUNT NUMBER DEFAULT 0,
    N_STATUS VARCHAR2(2) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_NOTICE_NO
START WITH 1
INCREMENT BY 1
NOCYCLE;

-- 문의/건의게시판
CREATE TABLE QNA (
 QNA_NO NUMBER PRIMARY KEY,
 QNA_TITLE VARCHAR(1000) NOT NULL,
 QNA_CONTENT VARCHAR(2000) NOT NULL,
 QNA_TYPE VARCHAR2(10) NOT NULL,
 QNA_WRITER VARCHAR2(100) NOT NULL,
 QNA_PW VARCHAR2(30),
 QNA_DATE DATE DEFAULT SYSDATE, 
 QNA_COUNT NUMBER,
 GROUPNO NUMBER NOT NULL,
 FK_SEQ NUMBER DEFAULT 0 NOT NULL,
 DEPTH_NO NUMBER DEFAULT 0 NOT NULL,
 QNA_STATUS VARCHAR2(2) DEFAULT 'N'
 );
 
 CREATE SEQUENCE QNA_NO;
 CREATE SEQUENCE SEQ_GROUPNO;

--SELECT * FROM TRES WHERE DEPT_DATE > SYSDATE - 1 ORDER BY DEPT_DATE DESC;
--SELECT * FROM TRES WHERE TRES_MEMID = '1' AND TRES_NO = (SELECT MAX(TRES_NO) FROM TRES WHERE TRES_MEMID = '1');
--SELECT COUNT(*) FROM TRES;
--SELECT * FROM TRES ORDER BY DEPT_DATE DESC;
--SELECT * FROM RES WHERE RES_MEMID = '1' AND RES_NO = (SELECT MAX(RES_NO) FROM RES WHERE RES_MEMID = '1');

--SELECT SEQ_TRES_NO.NEXTVAL FROM dual;

--ALTER SEQUENCE SEQ_RES_NO INCREMENT BY 21;
--ALTER SEQUENCE SEQ_TRES_NO INCREMENT BY 16;

--SELECT COUNT(*) FROM RES WHERE DEPT_DATE > SYSDATE - 1;

